# Default OS image is Ubuntu 14.04 LTS Trusty on Travis-CI for linux
language: c

dist: bionic

os:
  - linux

compiler:
  - gcc

env:
  - SRCDIR=vim/src

# sudo required to build AppImage (does apparently enable FUSE extensions)
sudo: required
branches:
  except:
    - /^v[0-9]/
addons:
  apt:
    packages:
      - autoconf
      - clang
      - lcov
      - gettext
      - libcanberra-dev
      - libperl-dev
      - python-dev
      - python3-dev
      - liblua5.3-dev
      - lua5.3
      - ruby-dev
      - tcl-dev
      - cscope
      - libgtk2.0-dev
      - desktop-file-utils
      - libtool-bin
services:
  - xvfb

before_install:
  - rvm reset
    # Really checkout the current branch (needed for commit/push later)
  - git checkout $TRAVIS_BRANCH
    # Update Vim
  - (cd vim && git checkout master && git pull)
  - export VIM_SUMMARY="$(git submodule summary vim)"
  - "[ -n \"$VIM_SUMMARY\" ] && export TRAVIS_TAG=$(cd vim && git describe --tags --abbrev=0) || true"

before_script:
  - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
  - sudo update-alternatives --install /usr/bin/lua lua /usr/bin/lua5.3 10
  - sudo bash vim/ci/load-snd-dummy.sh || true
  - sudo usermod -a -G audio $USER
  - do_test() { sg audio "sg $(id -gn) '$*'"; }

script:
  - scripts/build_vim.sh
  - ${SRCDIR}/vim --version
  - bash -ex scripts/appimage.sh
  - make -C vim/src/testdir
  # dump failed screen tests
  - scripts/dump_failed_screentests.sh

before_deploy:
  # wait 10 secs to be sure the test output is printed
  - sleep 10
  # Set up git user name and tag this commit
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "Committing, Tagging and Pushing..."
      openssl aes-256-cbc -K $encrypted_62bc4630de43_key -iv $encrypted_62bc4630de43_iv -in scripts/github_deploy_key.enc -out github_deploy_key -d
      chmod 600 github_deploy_key
      eval $(ssh-agent -s)
      ssh-add github_deploy_key
      git config --local user.name "Travis CI"
      git config --local user.email "travis@travis-ci.org"
      git remote add push-origin git@github.com:${TRAVIS_REPO_SLUG}.git
      git commit -m "Vim: $TRAVIS_TAG" -m "$VIM_SUMMARY" -m "$TRAVIS_BUILD_WEB_URL" -m "[ci skip]" vim
      git tag -f $TRAVIS_TAG -m "Vim: $TRAVIS_TAG"
      git push --follow-tags -u push-origin $TRAVIS_BRANCH
      ssh-add -D
      rm -f github_deploy_key
    else
      echo "Nothing to commit"
      unset TRAVIS_TAG
    fi
  - RELEASE_BODY="$(cat $TRAVIS_BUILD_DIR/release.body)"

deploy:
  - provider: releases
    api-key:
      # this is an encrypted personal github access token
      secure: KMER+Njo7lIQInBVGpqvBJqFCb8hxLYlOCC2jyleYzyo+cDZTXe/qNuBSXdTvAx8+WBCTyo/ZsEhsmDyR0a0C/3UxowXiKel8sOYw0STvLGg9IW9E1+gLCvkhc2M8zRSDFaPHBezsPFWxuqDkZAxzXCKfDpSk0bsRkYZHDums8aUvOAbTrp6tJpu5MaPOqOyrBcuvb2C442T94k1gEUJ/UtStZjyUN+6X3eKO9U24pwTUjPoNXOsOEFQktCRdV7w25B9OsivgNObswa27DiKjm1GGBmVXQPUmo2ft3G/GdQbdO8B0t/0DsIRTnLsCfH0jOXSx8ntrQLn6baJ1dF6wCin7Z9fb38z+MXeo/Ki8rx14j3/Jfle4WSQgOsXcuDEX2fhw18YIuNGe4ScOFrFZRgt2YSO+EFunRMpRgifA0UoPgS2u7qlQjH1N8R/StG1EumuP3zAs+jZkukDiUKS7QJ58yi/iQJsAwJUGHPHn/NjByaT+OPg6Lc8ubkxZ70kNfD75su6eM7csbS5vrSIhkNpOKpjTZWO33CKuT0ux5j4IJrLBwtwXEQINyhJCkbYXGYZzuywY3if+tDalj3Dq/8HzLVZg0XVlxBMEOmeDaff5kbfNjLk/gzhGHLhfB2lGJstU16gTiXJxmtSkcurmPcJJQVNPD1QvAYfTIwa2OY=
    name: "Vim: $TRAVIS_TAG"
    file:
      - "*.AppImage"
      - "*.zsync"
    file_glob: true
    overwrite: true
    body: "$RELEASE_BODY"
    skip_cleanup: true
    on:
      tags: true

after_script:
  # workaround for truncated output
  - sleep 10

# vim:set sts=2 sw=2 tw=0 et:
